import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import Script from "next/script";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {children}

        {/* External JS files added with the Script component */}

        {/* jQuery - if needed immediately, otherwise you can use lazyOnload */}
        <Script
          src="/js/jquery-1.11.0.min.js"
          strategy="beforeInteractive"
        />

        {/* Swiper JS from CDN */}
        <Script
          src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"
          strategy="beforeInteractive"
        />

        {/* Bootstrap JS from CDN */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />

        {/* Additional local scripts */}
        <Script src="/js/plugins.js" strategy="beforeInteractive" />
        <Script src="/js/script.js" />
      </body>
    </html>
  );
}
